language: ruby
rvm:
- 2.2

install:
 - nvm install 6.2
 - npm set progress=false && npm install
 - bundle install

script:
  - ./node_modules/.bin/gulp

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
